vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        projets:
            uri_prefix: /images/projets
            upload_destination: '%kernel.project_dir%/public/images/projets'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
